package fr.rockman18.funko.server.api.domainmodel.franchise;

// Generated 21 oct. 2015 16:04:04 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import fr.rockman18.funko.server.api.domainmodel.FunkoObject;
import fr.rockman18.funko.server.api.domainmodel.product.FunkoProduct;

/**
 * Patch generated by hbm2java
 */
@XmlRootElement
public class FunkoFranchise extends FunkoObject {

    private static final long serialVersionUID = 481089402777348234L;
    private Set<FunkoProduct> products = new HashSet<FunkoProduct>(0);

    public FunkoFranchise() {
    }

    public FunkoFranchise(int id) {
	super(id);
    }

    public FunkoFranchise(int id, String label, String url, String img, Set<FunkoProduct> products) {
	super(id, label, url, img);
	this.products = products;
    }

    @XmlTransient
    public Set<FunkoProduct> getProducts() {
	return this.products;
    }

    public void setProducts(Set<FunkoProduct> products) {
	this.products = products;
    }
}
