package fr.rockman18.funko.server.api.domainmodel.line;

// Generated 21 oct. 2015 16:04:04 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

import fr.rockman18.funko.server.api.domainmodel.FunkoObject;
import fr.rockman18.funko.server.api.domainmodel.product.FunkoProduct;

/**
 * Patch generated by hbm2java
 */
@XmlRootElement
public class FunkoLine extends FunkoObject {

    /**
     * {@link Object} obj : the object
     *
     */
    private static final long serialVersionUID = 6791032841593830206L;
    private int page;
    private FunkoLine parentLine;
    private Set<FunkoLine> subLines = new HashSet<FunkoLine>(0);
    private Set<FunkoProduct> products = new HashSet<FunkoProduct>(0);

    public FunkoLine() {
    }

    public FunkoLine(int id) {
	super(id);
    }

    public FunkoLine(int id, String label, String url, String img, int page, FunkoLine parentLine,
	    Set<FunkoLine> subLines, Set<FunkoProduct> products) {
	super(id, label, url, img);
	this.page = page;
	this.parentLine = parentLine;
	this.subLines = subLines;
	this.products = products;
    }

    public int getPage() {
	return page;
    }

    public void setPage(int page) {
	this.page = page;
    }

    public FunkoLine getParentLine() {
	return parentLine;
    }

    public void setParentLine(FunkoLine parentLine) {
	this.parentLine = parentLine;
    }

    @XmlTransient
    public Set<FunkoLine> getSubLines() {
	return subLines;
    }

    public void setSubLines(Set<FunkoLine> subLines) {
	this.subLines = subLines;
    }

    @XmlTransient
    public Set<FunkoProduct> getProducts() {
	return this.products;
    }

    public void setProducts(Set<FunkoProduct> products) {
	this.products = products;
    }

    @Override
    public String toString() {
	return (this.parentLine != null) ? String.join(" - ", this.parentLine.toString(), getLabel()) : getLabel();
    }
}
