package fr.rockman18.funko.server.api.domainmodel;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Patch generated by hbm2java
 */
@XmlRootElement
public abstract class FunkoObject implements java.io.Serializable {

    private static final long serialVersionUID = -5113561333126481624L;
    private int id;
    private String label;
    private String url;
    private String img;

    public FunkoObject() {
    }

    public FunkoObject(int id) {
	this.id = id;
    }

    public FunkoObject(int id, String label, String url, String img) {
	this.id = id;
	this.label = label;
	this.url = url;
	this.img = img;
    }

    public int getId() {
	return this.id;
    }

    public void setId(int id) {
	this.id = id;
    }

    public String getLabel() {
	return this.label;
    }

    public void setLabel(String label) {
	this.label = label;
    }

    public String getUrl() {
	return this.url;
    }

    public void setUrl(String url) {
	this.url = url;
    }

    public String getImg() {
	return this.img;
    }

    public void setImg(String img) {
	this.img = img;
    }
}
