#!/bin/bash -u

WEBAPP_FILE="[[project.runtime.install.directory]]/webapps/pms-server-webapp.war"
CONTEXT_FILE="[[project.runtime.install.directory]]/webapps/pms-server-webapp.xml"
JETTY_START_SCRIPT="/etc/init.d/jetty"


# Search jetty home directory. We use the script /etc/init.d/jetty.
#
# @return 0 if the java command has been found

setJettyHome() {
	if [ -n "${JETTY_HOME:-}" ]; then
		return 0
	fi
	if [ ! -x "$JETTY_START_SCRIPT" ]; then
		echo "Warning: $JETTY_START_SCRIPT not a file" 1>&2
		echo "Warning: unable to find jetty installation directory" 1>&2
		return 1
	fi
	JETTY_HOME=$($JETTY_START_SCRIPT status | sed -n 's/^JETTY_HOME *= *//p')
	if [ -z "$JETTY_HOME" ]; then
		echo "Warning: Unable to find jetty installation directory" 1>&2
		return 1
	fi
	return 0
}

if [ "${1:-}" = "purge" ]; then
	setJettyHome
	if [ $? -eq 0 ]; then
		LINK_NAME="$JETTY_HOME/webapps/$(basename $WEBAPP_FILE)"
		LINK_CONTEXT="$JETTY_HOME/webapps/$(basename $CONTEXT_FILE)"
		if [ -L "$LINK_NAME" ]; then
			rm -f "$LINK_NAME"
		fi
		if [ -e "$LINK_NAME" ]; then
			echo "Warning: $LINK_NAME not removed" 1>&2
		fi
		if [ -L "$LINK_CONTEXT" ]; then
			rm -f "$LINK_CONTEXT"
		fi
		if [ -e "$LINK_CONTEXT" ]; then
			echo "Warning: $LINK_CONTEXT not removed" 1>&2
		fi
	else
		echo "Warning: Unable to remove the symbolic link" 1>&2
	fi
fi

# We don't want to fail when it is not possible to delete the symbolic link
exit 0

